### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by Beau** [Laixer/Swabbr-Backend#11]
- [x] Total obtained and given likes
- [x] Total obtained reactions
- [x] Total given reactions
- [x] Total posted vlogs
- [ ] Total views

(Extracted from _"Requirements Swabbr App"_ 14-06-2019 - 11.3)

**Comment by tabeckers** [comment]
Has been implemented and moved to a new issue for fetching the user views. This is a complex problem on its own, depending on both wowza and our own playback services for uploaded vlogs, thus has its own separate issues
