### ISSUE TITLE
App notifications (action based)

### ISSUE THREAD

**Issue by Beau** [Laixer/Swabbr-Backend#14]
- [x] Een vlog verzoek (notificatie) vanuit de app! Maximaal drie keer per dag.Binnen drie minuten een vlog opnemen.
- [x] Als iemand live gaat (binnen de app als bericht/ buiten de app als notificatie).
- [ ] (basic functions, need to havevanuit admin panel
- [ ] Als er veel ongeziene vlogs binnende app voor de gebruiker staan.
- [ ] Als een gebruiker gedurende een lange tijd de app niet gebruikt heeft.
- [ ] Als een gebruiker gedurende een langetijd geen vlog heeft opgenomen.
- [x] Als volgers (of anderen bij een open account) veel Love Its hebben gegeven op een vlog die gemaakt is door de gebruiker.
- [x] Als iemand een reactie(privé of openbaar)heeft achtergelaten bij een van je vlogs (gebundeld als er veel reacties zijn)

(Extracted from _"Requirements Swabbr App"_ 14-06-2019)

**Comment by tabeckers** [comment]
All for version 1 are implemented
