### ISSUE TITLE
Disable Azure Cosmos Db shared throughput for production

### ISSUE THREAD

**Issue by Beau** [Laixer/Swabbr-Backend#21]
Account level throughput has been enabled for the CosmosDB during development to significantly reduce costs.

![image](https://user-images.githubusercontent.com/31695264/71970065-35aed980-3208-11ea-9bc0-6dd8b524271a.png)

($0.05/hour VS. $0.30/hour)

**Comment by tabeckers** [comment]
Cosmos DB is no longer used
