### ISSUE TITLE
User update properties

### ISSUE THREAD

**Issue by Beau** [Laixer/Swabbr-Backend#36]
Upon updating a user, should certain properties such as the country/gender/date of birth etc. be allowed to be changed? See `UserController.UpdateAsync`.

**Comment by tabeckers** [comment]
Required properties to be changed:

Voornaam
Achternaam
Geboortedatum
Geslacht
Nickname (hoe je op de app gezien zou willen worden)
Land
Wachtwoord
Profile image 
Interesses

**Comment by tabeckers** [comment]
Implemented
